name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.4

      - name: Build step
        run: "npm install --save-exact --save-dev esbuild && deno task transpile && deno task compile && deno task build && deno task package"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "kentasaito-test-70"
          entrypoint: "main.ts"
          root: "."
          exclude":
            - ./node_modules
            - ./.github
            - ./.vscode
            - ./deno.json
            - ./package.jso
